server.port: 8080
spring:
  application.name: myapp
  cloud.config.server.git:
    uri: https://github.com/spring-cloud-samples/config-repo
    #uri: https://github.com/liuruichao555/config-repo
    clone-on-start: true